### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by col6y** [seletskiy/hastur#7]
You may want to add a license to this to let others legally use it. I would recommend the MIT license, as it's pretty simple.

See also: http://choosealicense.com

**Comment by seletskiy** [comment]
Thanks!

**Comment by col6y** [comment]
I would recommend including the actual text of the license in your project, and make sure you understand its terms.

See [this page](http://choosealicense.com/licenses/mit/), especially the `How to apply this license` section.

**Comment by seletskiy** [comment]
@col6y: Hmm, OK, I'll do it. Basically, I am not too experienced in licensing because there aren't many people who are using my programs.

Thanks for the tip!
